### ISSUE TITLE
How do we attribute this?

### ISSUE THREAD

**Issue by abenrob** [openmaptiles/fiord-color-gl-style#4]
How do I attribute this map style if I plan on using it?

**Comment by abenrob** [comment]
Since it is based on Positron, should it maintain https://github.com/openmaptiles/positron-gl-style/blob/master/LICENSE.md#design-license-cc-by-40 ? The colors are different, but the _design_ is still the same concept.

**Comment by pathmapper** [comment]
Any update?

**Comment by pathmapper** [comment]
The missing license prevents adding the style to [Maputnik](https://github.com/maputnik/editor).

**Comment by pgassmann** [comment]
@petrsloup @klokan Can you add the LICENSE to the repository if it is based on Positron? https://github.com/openmaptiles/positron-gl-style/blob/master/LICENSE.md#design-license-cc-by-40

**Comment by TomPohys** [comment]
Fixed by https://github.com/openmaptiles/fiord-color-gl-style/pull/11.
